export default {
  primary: '#19514A',
  secondary: '#BB9B4E',
  background: '#F3F5F7',
  text: '#1D1818',
  white: '#FFFFFF',
  black: '#1D1818',
  gray: '#1D1818',
  lightGray: '#F7F7FA',
  darkGray: '#444',
  error: '#FF3B30',
  success: '#34C759',
  warning: '#FFCC00',
  info: '#007AFF',
  transparent: 'transparent',
  overlay: 'rgba(0, 0, 0, 0.5)',
  shadow: 'rgba(0, 0, 0, 0.1)',
  border: '#E5E5E5',
  placeholder: '#999',
  disabled: '#CCC',
  link: '#007AFF',
  card: '#FFFFFF',
  cardShadow: 'rgba(0, 0, 0, 0.05)',
  cardBorder: '#F0F0F0',
  cardBackground: '#FDF6ED',
  cardText: '#7a5c2e',
  cardTitle: '#19514A',
  cardDesc: '#666',
  cardAuthor: '#BB9B4E',
  cardIcon: '#19514A',
  cardIconBackground: '#F7F7FA',
  cardIconBorder: '#E5E5E5',
  cardIconShadow: 'rgba(0, 0, 0, 0.05)',
  cardIconHover: '#BB9B4E',
  cardIconHoverBackground: '#FDF6ED',
  cardIconHoverBorder: '#BB9B4E',
  cardIconHoverShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconActive: '#19514A',
  cardIconActiveBackground: '#F7F7FA',
  cardIconActiveBorder: '#19514A',
  cardIconActiveShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconDisabled: '#CCC',
  cardIconDisabledBackground: '#F7F7FA',
  cardIconDisabledBorder: '#E5E5E5',
  cardIconDisabledShadow: 'rgba(0, 0, 0, 0.05)',
  cardIconError: '#FF3B30',
  cardIconErrorBackground: '#F7F7FA',
  cardIconErrorBorder: '#FF3B30',
  cardIconErrorShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconSuccess: '#34C759',
  cardIconSuccessBackground: '#F7F7FA',
  cardIconSuccessBorder: '#34C759',
  cardIconSuccessShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconWarning: '#FFCC00',
  cardIconWarningBackground: '#F7F7FA',
  cardIconWarningBorder: '#FFCC00',
  cardIconWarningShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconInfo: '#007AFF',
  cardIconInfoBackground: '#F7F7FA',
  cardIconInfoBorder: '#007AFF',
  cardIconInfoShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconLink: '#007AFF',
  cardIconLinkBackground: '#F7F7FA',
  cardIconLinkBorder: '#007AFF',
  cardIconLinkShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconTransparent: 'transparent',
  cardIconTransparentBackground: 'transparent',
  cardIconTransparentBorder: 'transparent',
  cardIconTransparentShadow: 'transparent',
  cardIconOverlay: 'rgba(0, 0, 0, 0.5)',
  cardIconOverlayBackground: 'rgba(0, 0, 0, 0.5)',
  cardIconOverlayBorder: 'rgba(0, 0, 0, 0.5)',
  cardIconOverlayShadow: 'rgba(0, 0, 0, 0.5)',
  cardIconShadowShadow: 'rgba(0, 0, 0, 0.05)',
  cardIconShadowShadowBackground: 'rgba(0, 0, 0, 0.05)',
  cardIconShadowShadowBorder: 'rgba(0, 0, 0, 0.05)',
  cardIconShadowShadowShadow: 'rgba(0, 0, 0, 0.05)',
  cardIconHoverShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconHoverShadowShadowBackground: 'rgba(0, 0, 0, 0.1)',
  cardIconHoverShadowShadowBorder: 'rgba(0, 0, 0, 0.1)',
  cardIconHoverShadowShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconActiveShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconActiveShadowShadowBackground: 'rgba(0, 0, 0, 0.1)',
  cardIconActiveShadowShadowBorder: 'rgba(0, 0, 0, 0.1)',
  cardIconActiveShadowShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconDisabledShadowShadow: 'rgba(0, 0, 0, 0.05)',
  cardIconDisabledShadowShadowBackground: 'rgba(0, 0, 0, 0.05)',
  cardIconDisabledShadowShadowBorder: 'rgba(0, 0, 0, 0.05)',
  cardIconDisabledShadowShadowShadow: 'rgba(0, 0, 0, 0.05)',
  cardIconErrorShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconErrorShadowShadowBackground: 'rgba(0, 0, 0, 0.1)',
  cardIconErrorShadowShadowBorder: 'rgba(0, 0, 0, 0.1)',
  cardIconErrorShadowShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconSuccessShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconSuccessShadowShadowBackground: 'rgba(0, 0, 0, 0.1)',
  cardIconSuccessShadowShadowBorder: 'rgba(0, 0, 0, 0.1)',
  cardIconSuccessShadowShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconWarningShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconWarningShadowShadowBackground: 'rgba(0, 0, 0, 0.1)',
  cardIconWarningShadowShadowBorder: 'rgba(0, 0, 0, 0.1)',
  cardIconWarningShadowShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconInfoShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconInfoShadowShadowBackground: 'rgba(0, 0, 0, 0.1)',
  cardIconInfoShadowShadowBorder: 'rgba(0, 0, 0, 0.1)',
  cardIconInfoShadowShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconLinkShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconLinkShadowShadowBackground: 'rgba(0, 0, 0, 0.1)',
  cardIconLinkShadowShadowBorder: 'rgba(0, 0, 0, 0.1)',
  cardIconLinkShadowShadowShadow: 'rgba(0, 0, 0, 0.1)',
  cardIconTransparentShadowShadow: 'transparent',
  cardIconTransparentShadowShadowBackground: 'transparent',
  cardIconTransparentShadowShadowBorder: 'transparent',
  cardIconTransparentShadowShadowShadow: 'transparent',
  cardIconOverlayShadowShadow: 'rgba(0, 0, 0, 0.5)',
  cardIconOverlayShadowShadowBackground: 'rgba(0, 0, 0, 0.5)',
  cardIconOverlayShadowShadowBorder: 'rgba(0, 0, 0, 0.5)',
  cardIconOverlayShadowShadowShadow: 'rgba(0, 0, 0, 0.5)',
}; 